travis:
  secure:
    BINSTAR_TOKEN: OV5OwX8hbeHYG9T8OJFVHv2Oar9ljpugu5l8dSttfw0BWFqL9xF2DsxWUSA0ucIAmck0kOFXq6rPqU/vHzRYO3FdoJookdjHabu/SLrZFcyL4IKF+O4AKVE2UnJZAV2A9MPl6emX8saeD7fHYTAHulrx5FKXcLTsGWBWxvN/AZTtecLVkGrz5xhrEvBBcfpDsAR+j/zuYA4s4sk1BNZiR8Q2c6V1PmVPYNRjXE4d5My3GHXZEx2XpddpUzskiTft/2HErFfIMdMAkrt0gkC4KcSbJJfzU+vxSr7GFW8Fcj0U7Sz7socQqBiDEA9n7rCqrOIo3rRFQKC72s6znpLc0eISkArqRhBJvYEUAvpX2lkFikOeJu0pr4pLxMr4N6bKoGlhEbtLSV0jTeMpbxePWLGaaZQUm3FzRVWcuH/gIqzs/G6GipmOEzsgESk8nYEZEvcp3M7/mI9Pvptbu24LM3xYKgAvIrEFtLTE9ewG1PLnnKB7e5evKe+obraOgi0VtHFX+ZKSL0IoXuMNiddNENduV7Hca3khKFTY8PAAsAcLwzmPMV+8BWvGw3Dq+XIOUz7Jo+M6QOgGKNoROrHO+PQcjPNkw6NWzaMj5NKv2P2nHgHsSrtlSsrpcIQD0Gv/4IFkE/7C8AEb53qW3yp2HTN8PRC9UmYpOTq7xttAxKc=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
